---
- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Install mod_ssl
  yum:
    name: mod_ssl
    state: present

- name: Enable HTTP and HTTPS
  service:
    name: httpd
    state: started
    enabled: yes

- name: Restart Apache
  service:
    name: httpd
    state: restarted
