---
- name: Install Apache
  apt:
    name: apache2
    state: present
- name: Enable HTTP and HTTPS
  service:
    name: apache2
    state: started
    enabled: yes

- name: Enable SSL module
  command: a2enmod ssl

- name: Restart Apache
  service:
    name: apache2
    state: restarted
    
