---
- name: Playbook | Updating packages with -y
  hosts: tomcat
  become: yes
  tasks:
    - name: update packages
      yum:
        name: '*'
        state: latest

- name: setup Tomcat Server
  hosts: tomcat
  become: yes
  roles:
    - tomcat


- name: creating users on the servers 
  user:
    name: '{{item}}'
    state: absent
    with_items:
      - snk
      - karthik
      - naveena
      - ramcharan
      - chiru
      - nagarjuna
      - venkatesh
      - mahesh
      - prabhas
      - pawan
- name: Playbook | to create | file
  hosts: tomcat
  become: yes
  tasks:
    - name: creating a directory
      file:
      path: /tmp/ansible
      state: directory
      mode: 0755

    - name: creating a file inside the directory
      file:
        path: "{{item}}"
        state: touch
      with_items:
        - /tmp/ansible/file1
        - /tmp/ansible/file2
        - /tmp/ansible/file3
        - /tmp/ansible/file4
        - /tmp/ansible/file5

