---
# - name: Playbook | Updating packages with -y
#   hosts: tomcat
#   become: yes
#   tasks:
#     - name: update packages
#       yum:
#         name: '*'
#         state: latest

- name: setup Tomcat Server
  hosts: tomcat
  become: yes
  roles:
    - tomcat

- name: creating users on the servers 
  hosts: tomcat
  become: yes
  tasks: 
    - name: creating users
      user:
        name: '{{ item }}'
        state: absent
      loop:
        - snk
        - karthik
        - naveena
        - ramcharan
        - chiru
        - nagarjuna
        - venkatesh
        - mahesh
        - prabhas
        - pawan
 
- name: Playbook | to create | file
  hosts: tomcat
  become: yes
  tasks:
    - name: creating a directory
      file:
        path: /tmp/ansible
        state: directory
        mode: '0755'

    - name: creating a file inside the directory
      file:
        path: /tmp/ansible/example.txt
        state: touch

